### ISSUE TITLE
Add Search Linked tickets functionality

### ISSUE THREAD

**Issue by gianpaj** [jimoleary/mongo-jira#4]
See here:
http://stackoverflow.com/questions/3918255/jira-searching-issues-by-issue-links

**Comment by gianpaj** [comment]
I believe we fixed this but can't remember how:

```
$ jira query 'project=CS and issue in linkedIssues(SERVER-7471)'
error: undefined method `fixVersions' for #<JIRA::Resource::Issue:0x007f9050d9d748>. Use --trace to view backtrace
```

But we should be able just to allow multiple SERVER tickets. Instead of:

```
$ jira query 'project=CS and (issue in linkedIssues(SERVER-123) or issue in linkedIssues(SERVER-234))'
```

https://confluence.atlassian.com/display/JIRA042/Advanced+Searching?clicked=jirahelp#AdvancedSearching-linkedIssues

**Comment by gianpaj** [comment]
```
/Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/jira-ruby-0.1.2/lib/jira/base.rb:305:in `method_missing': undefined method `fixVersions' for #<JIRA::Resource::Issue:0x007fb1f9d1b228> (NoMethodError)
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/jira-ruby-0.1.2/lib/jira/resource/issue.rb:63:in `method_missing'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/core_ext/object/try.rb:36:in `try'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/mongo-jira-0.0.2/bin/jira:375:in `fix_versions'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/mongo-jira-0.0.2/bin/jira:349:in `header'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/mongo-jira-0.0.2/bin/jira:290:in `block (3 levels) in <top (required)>'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/mongo-jira-0.0.2/bin/jira:288:in `each'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/mongo-jira-0.0.2/bin/jira:288:in `block (2 levels) in <top (required)>'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/commander-4.1.5/lib/commander/command.rb:180:in `call'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/commander-4.1.5/lib/commander/command.rb:180:in `call'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/commander-4.1.5/lib/commander/command.rb:155:in `run'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/commander-4.1.5/lib/commander/runner.rb:402:in `run_active_command'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/commander-4.1.5/lib/commander/runner.rb:78:in `run!'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/commander-4.1.5/lib/commander/delegates.rb:11:in `run!'
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/commander-4.1.5/lib/commander/import.rb:10:in `block in <top (required)>'
```

**Comment by gianpaj** [comment]
I'm guess it's something to do with my version of ruby.

```
$ jira --version
jira 0.0.3
$ jira query 'project=CS and issue in linkedIssues(SERVER-7471)' --trace
/Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/jira-ruby-0.1.2/lib/jira/base.rb:305:in `method_missing': undefined method `fixVersions' for #<JIRA::Resource::Issue:0x007fd2fbca6d88> (NoMethodError)
    from /Users/gianfranco/.rvm/gems/ruby-1.9.3-p194/gems/jira-ruby-0.1.2/lib/jira/resource/issue.rb:63:in `method_missing'
...
```

**Comment by gianpaj** [comment]
sorry we still need to make the syntax simper

**Comment by jimoleary** [comment]
I kind of want to keep the syntax the same as jira so that you can search the same way

**Comment by gianpaj** [comment]
I installed the gem yesterday and `--version` returns `0.0.0`.
Did you sent me a newer version via email? can you push the latest here and to rubygems?
